export const GET_PAGE_PRODUCTS = 'GET_PAGE_PRODUCTS';
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const GET_TREE_CATEGORIES = 'GET_TREE_CATEGORIES';